# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orb < Formula
  desc "AI-powered codebase indexing and analysis CLI tool"
  homepage "https://github.com/augur-ai/augur-jobs"
  version "0.0.50"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/augur-ai/homebrew-tap/releases/download/v0.0.50/orb_0.0.50_linux_amd64.tar.gz"
    sha256 "6657a92acfcd82a8d77251e198e1ee502d28f0656a154ef3f53bd24028e5d8ad"
    def install
      bin.install "orb"
    end
  end
  if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/augur-ai/homebrew-tap/releases/download/v0.0.50/orb_0.0.50_linux_arm64.tar.gz"
    sha256 "8c60ab514adeff274ae557012c97afe2447f2996b8bde6695cbba2a3bc1dcbc6"
    def install
      bin.install "orb"
    end
  end

  test do
    system "#{bin}/orb", "--version"
  end
end
